#!/bin/bash

if [ "$EUID" -eq 0 ]; then
    echo "Please run as regular user"
    exit
fi

NEW_DISORD_ARCHIVE=$(ls -Art ~/Downloads/discord-*.tar.gz | tail -n 1)
DISCORD_LOCATION=/opt/discord

tar -xf $NEW_DISORD_ARCHIVE -C /tmp/
rm -rf $DISCORD_LOCATION
sudo mv /tmp/Discord $DISCORD_LOCATION
rm -rf $NEW_DISORD_ARCHIVE
